# Generated by Django 4.0 on 2022-01-06 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_hardware'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='isAvailable',
            field=models.BooleanField(),
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_start', models.DateTimeField(verbose_name='start time and date of loan')),
                ('loan_return', models.DateTimeField(help_text='return time and date of loan')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lrcdatabaseuser')),
                ('target', models.ForeignKey(help_text='Equipment being requested', on_delete=django.db.models.deletion.CASCADE, related_name='hardware_requested', to='main.hardware')),
            ],
        ),
    ]
